// Run against an application with a real, already-running Ollama on port 11435.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.IQ_CHROMIUM,args:['--no-sandbox','--disable-gpu'],headless:true});const results=[];try{
const p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(20000);const errors=[];let dialogs=0;p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{dialogs++;await d.dismiss();});
await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.querySelector('#skill-choice').options.length>1);
await p.screenshot({path:process.env.IQ_QA_DIR+'/product-home.png',fullPage:true});
await p.locator('#message').fill('Hola');await p.locator('#send').click();await p.waitForFunction(()=>document.querySelector('.message.assistant'));
assert.match(await p.locator('.message.assistant').innerText(),/Herramienta local/);results.push('Saludo sin inferencia');
await p.locator('[data-view=settings]').click();await p.getByText('Motor externo ya instalado',{exact:false}).click();await p.locator('#manual-backend').selectOption('ollama');await p.locator('#manual-url').fill('http://127.0.0.1:11435');await p.locator('#manual-model').fill('qwen3:4b');await p.getByRole('button',{name:'Conectar este motor',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#notice').textContent.startsWith('Motor configurado'));
await p.locator('#new-chat').click();await p.locator('#chat-file').setInputFiles({name:'condiciones.txt',mimeType:'text/plain',buffer:Buffer.from('El soporte está disponible de lunes a viernes de 9 a 18. Las urgencias fuera de horario tienen un costo adicional de 50 USD por incidente.')});await p.waitForFunction(()=>document.querySelector('#attached').children.length===1);
await p.locator('#message').fill('¿Las urgencias fuera de horario están incluidas sin cargo? Respondé brevemente.');await p.locator('#send').click();await p.waitForFunction(()=>document.querySelector('.message.assistant'),{},{timeout:180000});
const answer=await p.locator('.message.assistant').innerText();assert.match(answer,/\bNo\b|costo adicional|no est[aá]n incluidas/i);assert.equal(await p.locator('.message.assistant details').count()>0,true);results.push('Pregunta documental real y citas');
await p.locator('.message.assistant summary').first().click();assert.match(await p.locator('.message.assistant blockquote').first().innerText(),/50 USD/);await p.screenshot({path:process.env.IQ_QA_DIR+'/product-document.png',fullPage:true});
const dl=p.waitForEvent('download');await p.getByRole('button',{name:'Descargar informe',exact:true}).click();assert.match(fs.readFileSync(await(await dl).path(),'utf8'),/Fuente:/);results.push('Exportación de informe');
await p.locator('#new-chat').click();await p.locator('#message').fill('Redactá un correo de dos frases para pedir una reunión mañana a la tarde.');await p.locator('#send').click();await p.waitForFunction(()=>document.querySelector('.message.assistant'),{},{timeout:180000});
const draft=await p.locator('.message.assistant').innerText();assert.doesNotMatch(draft,/cita no coincide|formato esperado/);assert.match(draft,/reuni[oó]n|reunir/i);results.push('Redacción real sin archivos');
await p.locator('[data-view=skills]').click();await p.locator('#new-skill').click();for(const [key,value] of Object.entries({name:'Acuse de prueba',description:'Confirmar recepción',instructions:'Ante cualquier pedido, respondé exactamente: RECIBIDO. No hace falta información adicional.',example:'Confirmá este pedido',expected:'RECIBIDO'}))await p.locator('#skill-'+key).fill(value);await p.getByRole('button',{name:'Guardar versión para probar'}).click();await p.waitForFunction(()=>document.querySelector('#skill-editor').hidden);
await p.getByRole('button',{name:'Probar ejemplo',exact:true}).first().click();await p.waitForFunction(()=>document.querySelector('.message.assistant .message-body')?.textContent.includes('RECIBIDO'),{},{timeout:180000});await p.locator('[data-view=skills]').click();await p.getByRole('button',{name:'Activar versión revisada',exact:true}).click();await p.waitForFunction(()=>[...document.querySelectorAll('#skill-choice option')].some(o=>o.textContent==='Acuse de prueba'));results.push('Crear, probar con modelo y activar capacidad');
await p.locator('[data-view=documents]').click();assert.ok(await p.locator('#document-list .card').count()>0);await p.locator('[data-view=activity]').click();assert.ok(await p.locator('.activity-item').count()>=4);results.push('Documentos y actividad');
await p.locator('[data-view=settings]').click();const backup=p.waitForEvent('download');await p.locator('#backup').click();const data=fs.readFileSync(await(await backup).path());assert.equal(data.subarray(0,2).toString(),'PK');results.push('Respaldo SQLite');
await p.locator('[data-view=chat]').click();await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await p.screenshot({path:process.env.IQ_QA_DIR+'/product-mobile.png',fullPage:true});results.push('Diseño móvil sin desbordamiento');
assert.deepEqual(errors,[]);assert.equal(dialogs,0);fs.writeFileSync(process.env.IQ_QA_DIR+'/browser-results.json',JSON.stringify({passed:results,errors},null,2));console.log(JSON.stringify({passed:results,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
